version: "2"
checks:
  file-lines:
    enabled: false
  method-count:
    config:
      threshold: 75
  method-lines:
    config:
      threshold: 250
plugins:
  phan:
    enabled: true
    config:
      file_extensions: "php"
      dead-code-detection: true
    checks:
      PhanUndeclaredClassMethod:
        enabled: false
      PhanUndeclaredConstant:
        enabled: false
      PhanUndeclaredFunction:
        enabled: false
      PhanUndeclaredTypeParameter:
        enabled: false
      PhanUndeclaredClassConstant:
        enabled: false
      PhanUndeclaredExtendedClass:
        enabled: false
      PhanUnreferencedClass:
        enabled: false
      PhanUndeclaredMethod:
        enabled: false
      PhanUndeclaredTypeReturnType:
        enabled: false
      PhanUndeclaredTypeProperty:
        enabled: false
      PhanUnreferencedPublicMethod:
        enabled: false
      PhanUndeclaredProperty:
        enabled: false
      PhanUnreferencedClosure:
        enabled: false
      PhanUnreferencedProtectedMethod:
        enabled: false
      PhanUndeclaredClassInstanceof:
        enabled: false
      PhanUndeclaredClass:
        enabled: false  
